# Generated by Django 5.1.15 on 2026-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
