# Generated by Django 5.1.15 on 2026-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0002_loginhistory_registereduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
